Models/JobList.cs
using Fpt.Areas.Data;

namespace Fpt.Models
{
    public class JobList
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string RequiredSkills { get; set; }
        public DateTime DateTime { get; set; }


        public string ApplicationId { get; set; }
        public virtual Application? Application { get; set; }
        public virtual ICollection<JobApplication>? JobApplication { get; set; }
    }
}

Controllers/JobListsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fpt.Data;
using Fpt.Models;
using System.Security.Claims;

namespace Fpt.Controllers
{
    public class JobListsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JobListsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Apply(string searchString)
        {
            var jobLists = from j in _context.JobList
                           select j;

            if (!string.IsNullOrEmpty(searchString))
            {
                jobLists = jobLists.Where(s => s.Name.Contains(searchString) || s.Description.Contains(searchString));
            }
            var applicationDbContext = jobLists.Include(j => j.Application);

            return View(await applicationDbContext.ToListAsync());
        }
    

            public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _context.Users.FindAsync(userId);

            if (user.UserRole == "Employer")
            {
                var jobLists = await _context.JobList
                    .Where(j => j.ApplicationId == userId)
                    .Include(j => j.Application)
                    .ToListAsync();

                return View(jobLists);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobListing = await _context.JobList
                .Include(j => j.Application)
                .Include(j => j.JobApplication)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (jobListing == null)
            {
                return NotFound();
            }

            return View(jobListing);
        }

        public IActionResult Create()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _context.Users.Find(userId);

            if (user.UserRole == "Employer")
            {
                var jobList = new JobList
                {
                    ApplicationId = userId
                };

                return View(jobList);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,RequiredSkills,DateTime,ApplicationId")] JobList jobList)
        {
            if (ModelState.IsValid)
            {
                _context.Add(jobList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(jobList);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobListing = await _context.JobList.FindAsync(id);

            if (jobListing == null)
            {
                return NotFound();
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _context.Users.Find(userId);

            if (user.UserRole != "Employer")
            {
                return RedirectToAction("Index", "Home");
            }

            return View(jobListing);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,RequiredSkills,DateTime,ApplicationId")] JobList jobList)
        {
            if (id != jobList.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jobList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobListExists(jobList.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(jobList);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobListing = await _context.JobList
                .Include(j => j.Application)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (jobListing == null)
            {
                return NotFound();
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _context.Users.Find(userId);

            if (user.UserRole != "Employer")
            {
                return RedirectToAction("Index", "Home");
            }

            return View(jobListing);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var jobListing = await _context.JobList.FindAsync(id);
            if (jobListing != null)
            {
                _context.JobList.Remove(jobListing);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool JobListExists(int id)
        {
            return _context.JobList.Any(e => e.Id == id);
        }
    }
}

Views/JobLists/Apply.cshtml
@model IEnumerable<Fpt.Models.JobList>

@{
    ViewData["Title"] = "Apply";
}

<h1>Lists of Job</h1>
<form asp-controller="JobLists" asp-action="Apply">
    <p>
        <input type="text" name="searchString" />
        <input type="submit" value="Search" />
    </p>

</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequiredSkills)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Application)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequiredSkills)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Application.Id)
                </td>
                <td>
                    <a href="/JobApplications/Create?jobListId=@item.Id">Apply</a> |
                </td>
            </tr>
        }
    </tbody>
</table>

Views/JobLists/Create.cshtml
@model Fpt.Models.JobList

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>JobList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequiredSkills" class="control-label"></label>
                <input asp-for="RequiredSkills" class="form-control" />
                <span asp-validation-for="RequiredSkills" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTime" class="control-label"></label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationId" class="control-label"></label>
                <input asp-for="ApplicationId" class="form-control" readonly />
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/JobLists/Delete.cshtml
@model Fpt.Models.JobList

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>JobList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequiredSkills)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequiredSkills)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Application)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Application.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/JobLists/Details.cshtml
@model Fpt.Models.JobList

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>JobList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequiredSkills)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequiredSkills)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Application)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Application.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
<div>
    <h4>Job Applications</h4>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.JobApplication.First().Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.JobApplication.First().DescribeYourself)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var jobApplication in Model.JobApplication)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => jobApplication.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => jobApplication.DescribeYourself)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/JobLists/Edit.cshtml
@model Fpt.Models.JobList

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>JobList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequiredSkills" class="control-label"></label>
                <input asp-for="RequiredSkills" class="form-control" />
                <span asp-validation-for="RequiredSkills" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTime" class="control-label"></label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationId" class="control-label"></label>
                <select asp-for="ApplicationId" class="form-control" asp-items="ViewBag.ApplicationId"></select>
                <span asp-validation-for="ApplicationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/JobLists/Index.cshtml
@model IEnumerable<Fpt.Models.JobList>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequiredSkills)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Application)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RequiredSkills)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Application.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>